# -*- coding: utf-8 -*-
"""存储 + 初始化 + 种子数据。

默认 SQLite；设 DATABASE_URL=postgres://... 则走 Postgres。
流水账(ledger)是唯一真相源：余额=SUM(全部 delta)、升级阳光=SUM(非 redeem/银行存取 的 delta，含取消和扣分)、
等级/连击由净增阳光与日期推导。兑换不掉级；取消打卡、约定扣分会减少升级进度。
"""
import hashlib
import hmac
import json
import os
import sqlite3
from datetime import datetime
from pathlib import Path

BASE = Path(__file__).parent
SEED_JSON = BASE.parent / "data" / "tasks.seed.json"
SEED_MULTI = BASE.parent / "data" / "tasks.seed.multi.json"


def db_path() -> Path:
    return Path(os.environ.get("SUNSHINE_DB", BASE / "sunshine.db"))


DB_PATH = db_path()

# 兑换商店（P0 内置示例，家长后续在管理端增删改）
REWARDS = [
    {"id": "tv30",  "name": "看动画30分钟",  "price": 30,  "category": "娱乐", "need_approval": 1},
    {"id": "park",  "name": "周末去游乐场",  "price": 100, "category": "出行", "need_approval": 1},
    {"id": "wish",  "name": "心愿礼物",      "price": 200, "category": "礼物", "need_approval": 1},
]

# 等级（累计获得阳光阈值，消费不掉级）
# 参照 Duolingo/ClassDojo：前期密集升级给即时反馈，后期门槛递增；emoji 递进形象
RANKS_VER = "v4"
DEFAULT_FAMILY = "f-default"
DEFAULT_KID = "kid-default"
DEFAULT_PARENT = "parent-default"
ALL_SUBJECTS = ["语文", "数学", "英语", "科学", "道法", "体育", "音美", "综合", "围棋"]

# 满级 5000 = 约一学期坚持（日产出 ~60），共 10 档，前期密度后期递增
RANKS = [
    {"id": "r1",  "name": "阳光萌新",   "min_sunshine": 0,    "icon": "sprout"},
    {"id": "r2",  "name": "阳光小苗",   "min_sunshine": 50,   "icon": "leaf"},
    {"id": "r3",  "name": "阳光小能手", "min_sunshine": 150,  "icon": "flower"},
    {"id": "r4",  "name": "阳光达人",   "min_sunshine": 350,  "icon": "star"},
    {"id": "r5",  "name": "阳光之星",   "min_sunshine": 700,  "icon": "flame"},
    {"id": "r6",  "name": "阳光学霸",   "min_sunshine": 1200, "icon": "trophy"},
    {"id": "r7",  "name": "阳光大师",   "min_sunshine": 2000, "icon": "medal"},
    {"id": "r8",  "name": "阳光传说",   "min_sunshine": 3000, "icon": "gem"},
    {"id": "r9",  "name": "阳光战神",   "min_sunshine": 4000, "icon": "rocket"},
    {"id": "r10", "name": "传奇学神",   "min_sunshine": 5000, "icon": "crown"},
]


def is_postgres() -> bool:
    return os.environ.get("DATABASE_URL", "").startswith("postgres")


def _schema():
    pk = ("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if is_postgres() else "INTEGER PRIMARY KEY AUTOINCREMENT")
    return f"""
CREATE TABLE IF NOT EXISTS subjects (id TEXT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS terms (id TEXT PRIMARY KEY, label TEXT, grade TEXT, term TEXT, version TEXT);
CREATE TABLE IF NOT EXISTS units (id TEXT PRIMARY KEY, subject_id TEXT, term_id TEXT, seq INTEGER, name TEXT);
CREATE TABLE IF NOT EXISTS tasks (
  id TEXT PRIMARY KEY, subject_id TEXT, unit_id TEXT, action TEXT, title TEXT, detail TEXT DEFAULT '', sunshine INTEGER, sort INTEGER, custom INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS daily_tasks (
  id TEXT PRIMARY KEY, subject_id TEXT, name TEXT, sunshine INTEGER, frequency TEXT,
  bonus_type TEXT, bonus_per_metric INTEGER, note TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS daily_metrics (
  task_id TEXT, id TEXT, label TEXT, unit TEXT, direction TEXT, note TEXT, PRIMARY KEY (task_id, id));
CREATE TABLE IF NOT EXISTS rewards (
  id TEXT PRIMARY KEY, name TEXT, price INTEGER, category TEXT, need_approval INTEGER);
CREATE TABLE IF NOT EXISTS ranks (
  id TEXT PRIMARY KEY, name TEXT, min_sunshine INTEGER, sort INTEGER, icon TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS checkins (
  id {pk}, date TEXT NOT NULL, sunshine INTEGER, created_at TEXT);
CREATE TABLE IF NOT EXISTS completions (
  id {pk}, task_id TEXT NOT NULL, date TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'completed', sunshine INTEGER NOT NULL, metrics TEXT, created_at TEXT,
  kind TEXT NOT NULL DEFAULT 'unit');
CREATE TABLE IF NOT EXISTS ledger (
  id {pk}, date TEXT NOT NULL, delta INTEGER NOT NULL,
  reason TEXT, ref_id TEXT, note TEXT, created_at TEXT,
  account TEXT NOT NULL DEFAULT 'pocket');
CREATE TABLE IF NOT EXISTS redemptions (
  id {pk}, reward_id TEXT, date TEXT, price INTEGER,
  status TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE IF NOT EXISTS tests (
  id {pk}, subject_id TEXT, unit_id TEXT, score INTEGER, sunshine INTEGER,
  note TEXT, date TEXT, created_at TEXT);
"""


class _Row(dict):
    """sqlite3.Row 兼容：r['col'] / r[0] / dict(r)。缺列返回 None。"""
    def __getitem__(self, key):
        if isinstance(key, int):
            return list(dict.values(self))[key]
        return dict.get(self, key)


def _pg_row_factory(cursor):
    cols = [c.name for c in (cursor.description or ())]
    def make(values):
        return _Row(zip(cols, values))
    return make


def _pg_query(q):
    """引号外 ? → 占位；再 %→%%（psycopg 线格式，服务端仍是 %）。字面量 '?' 不动。"""
    out = []
    i, n = 0, len(q)
    while i < n:
        ch = q[i]
        if ch == "'":
            out.append(ch)
            i += 1
            while i < n:
                out.append(q[i])
                if q[i] == "'":
                    if i + 1 < n and q[i + 1] == "'":
                        out.append("'")
                        i += 2
                        continue
                    i += 1
                    break
                i += 1
            continue
        out.append("\x00" if ch == "?" else ch)
        i += 1
    return "".join(out).replace("%", "%%").replace("\x00", "%s")


class _Conn:
    """统一 execute：SQL 继续写 ?，PG 侧换成 %s。"""
    def __init__(self, raw, pg: bool):
        self._raw = raw
        self.pg = pg

    def execute(self, q, params=()):
        if self.pg:
            q = _pg_query(q)
        return self._raw.execute(q, params)

    def executescript(self, script):
        if not self.pg:
            return self._raw.executescript(script)
        # ponytail: 按 ; 切，DDL 字符串里别塞分号
        for stmt in script.split(";"):
            stmt = stmt.strip()
            if stmt:
                self._raw.execute(stmt)

    def commit(self):
        self._raw.commit()

    def rollback(self):
        self._raw.rollback()

    def close(self):
        self._raw.close()


PBKDF2_ITERS = 600_000  # OWASP PBKDF2-SHA256


def hash_pin(pin: str) -> str:
    salt = os.urandom(16)
    dk = hashlib.pbkdf2_hmac("sha256", pin.encode(), salt, PBKDF2_ITERS)
    return f"pbkdf2${PBKDF2_ITERS}${salt.hex()}${dk.hex()}"


def verify_pin(pin: str, stored: str) -> bool:
    if not pin or not stored:
        return False
    try:
        algo, iters, salt_hex, hash_hex = stored.split("$")
        if algo != "pbkdf2":
            return False
        dk = hashlib.pbkdf2_hmac("sha256", pin.encode(), bytes.fromhex(salt_hex), int(iters))
        return hmac.compare_digest(dk.hex(), hash_hex)
    except (ValueError, TypeError):
        return False


def secret_key() -> str:
    env = os.environ.get("SECRET_KEY")
    if env:
        return env
    # 持久化到数据目录，避免容器重启丢失
    data_dir = Path(os.environ.get("SUNSHINE_DB", BASE / "sunshine.db")).parent
    data_dir.mkdir(parents=True, exist_ok=True)
    path = data_dir / ".secret_key"
    if path.exists():
        return path.read_text().strip()
    k = os.urandom(32).hex()
    path.write_text(k)
    return k


def apply_scope(conn, family_id, kid_id):
    # ponytail: session GUC（无连接池）；上池后改 SET LOCAL + 每请求复位
    # 请求路径只许 get_conn() 调这里。db.connect() 不设 GUC：未设时 RLS 匹配空串，查活动表=0 行。
    if not conn.pg:
        return
    if family_id:
        conn.execute("SELECT set_config('app.family_id', ?, false)", (family_id,))
    if kid_id:
        conn.execute("SELECT set_config('app.kid_id', ?, false)", (kid_id,))


def now() -> str:
    return datetime.now().isoformat(timespec="seconds")


def today() -> str:
    return datetime.now().strftime("%Y-%m-%d")


def connect(admin=False):
    if is_postgres():
        import psycopg
        if admin:
            url = os.environ["DATABASE_URL"]  # superuser，只跑迁移
        else:
            url = os.environ.get("DATABASE_APP_URL")
            if not url:
                raise RuntimeError("DATABASE_APP_URL required (login as sunshine_app; superuser bypasses RLS)")
        raw = psycopg.connect(url, row_factory=_pg_row_factory)
        return _Conn(raw, True)  # 不设 GUC。业务查询用 get_conn()；这里只碰无 RLS 表（users/settings）
    raw = sqlite3.connect(db_path())
    raw.row_factory = sqlite3.Row
    return _Conn(raw, False)


def insert(conn, sql, params=()):
    """INSERT … [ON CONFLICT DO NOTHING] RETURNING id。冲突返回 None。"""
    sql = sql.rstrip().rstrip(";").rstrip()
    if " returning " not in sql.lower():
        sql = sql + " RETURNING id"
    row = conn.execute(sql, params).fetchone()
    return None if row is None else row[0]


def load_seed():
    """优先读多学期 seed；旧单学期文件自动包成 terms[]。"""
    path = SEED_MULTI if SEED_MULTI.exists() else SEED_JSON
    data = json.loads(path.read_text(encoding="utf-8"))
    if "terms" not in data and "term" in data:
        data["terms"] = [data["term"]]
    return data


def initialize_family(conn, family_id):
    """给新家庭灌默认商店/等级。已有行不覆盖。"""
    n = conn.execute("SELECT COUNT(*) FROM rewards WHERE family_id=?", (family_id,)).fetchone()[0]
    if n == 0:
        for r in REWARDS:
            conn.execute(
                "INSERT INTO rewards(id,name,price,category,need_approval,family_id) VALUES(?,?,?,?,?,?)",
                (family_id + "-" + r["id"], r["name"], r["price"], r["category"], r["need_approval"], family_id))
    n = conn.execute("SELECT COUNT(*) FROM ranks WHERE family_id=?", (family_id,)).fetchone()[0]
    if n == 0:
        for i, r in enumerate(RANKS):
            conn.execute(
                "INSERT INTO ranks(id,name,min_sunshine,sort,icon,family_id) VALUES(?,?,?,?,?,?)",
                (family_id + "-" + r["id"], r["name"], r["min_sunshine"], i, r.get("icon", ""), family_id))


def seed_ranks(conn):
    """缺档补上；已有档只把 emoji icon 改成代号，不覆盖家长改的名字/阈值。"""
    initialize_family(conn, DEFAULT_FAMILY)
    emoji = {"🌱":"sprout","🌿":"leaf","🌼":"flower","⭐":"star","🔥":"flame","🏆":"trophy","🥇":"medal","💎":"gem","🚀":"rocket","👑":"crown"}
    for e, code in emoji.items():
        conn.execute("UPDATE ranks SET icon=? WHERE icon=?", (code, e))
    set_setting(conn, "ranks_ver", RANKS_VER)


def _upsert_unit(conn, u):
    ver = unit_edition(u["subject"], u["id"])
    conn.execute(
        "INSERT INTO units(id,subject_id,term_id,seq,name,version) VALUES(?,?,?,?,?,?) "
        "ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id, term_id=excluded.term_id, "
        "seq=excluded.seq, name=excluded.name, version=excluded.version",
        (u["id"], u["subject"], u["term_id"], u["seq"], u["name"], ver))


def seed(conn):
    data = load_seed()
    conn.execute("DELETE FROM terms")
    for term in data.get("terms", []):
        conn.execute("INSERT INTO terms(id,label,grade,term,version) VALUES(?,?,?,?,?)",
                     (term["id"], term["label"], term["grade"], term["term"], term["version"]))
    for s in ALL_SUBJECTS:
        conn.execute("INSERT INTO subjects(id,name) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name",
                     (s, s))
    for u in data["units"]:
        _upsert_unit(conn, u)
    for t in data["tasks"]:
        conn.execute(
            "INSERT INTO tasks(id,subject_id,unit_id,action,title,detail,sunshine,sort,custom) "
            "VALUES(?,?,?,?,?,?,?,?,0) "
            "ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id, unit_id=excluded.unit_id, "
            "action=excluded.action, title=excluded.title, detail=excluded.detail, "
            "sunshine=excluded.sunshine, sort=excluded.sort, custom=excluded.custom",
            (t["id"], t["subject"], t["unit_id"], t["action"], t["title"], t.get("detail", ""), t["sunshine"], t["sort"]))
    for d in data["daily_tasks"]:
        br = d.get("bonus_rule") or {}
        conn.execute(
            "INSERT INTO daily_tasks(id,subject_id,name,sunshine,frequency,bonus_type,bonus_per_metric,note) "
            "VALUES(?,?,?,?,?,?,?,?) "
            "ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id, name=excluded.name, "
            "sunshine=excluded.sunshine, frequency=excluded.frequency, bonus_type=excluded.bonus_type, "
            "bonus_per_metric=excluded.bonus_per_metric, note=excluded.note",
            (d["id"], d["subject"], d["name"], d["sunshine"], d["frequency"],
             br.get("type"), br.get("per_metric"), d.get("note", "")))
        for m in d.get("metrics", []):
            conn.execute(
                "INSERT INTO daily_metrics(task_id,id,label,unit,direction,note) "
                "VALUES(?,?,?,?,?,?) "
                "ON CONFLICT(task_id, id) DO UPDATE SET label=excluded.label, unit=excluded.unit, "
                "direction=excluded.direction, note=excluded.note",
                (d["id"], m["id"], m["label"], m["unit"], m["direction"], m.get("note")))
    initialize_family(conn, DEFAULT_FAMILY)
    seed_ranks(conn)
    set_setting(conn, "curriculum_ver", data.get("curriculum_ver", ""))


def apply_curriculum(conn):
    """已有库：只刷新系统任务/单元，保留自定义任务和流水。"""
    data = load_seed()
    ver = data.get("curriculum_ver", "")
    if get_setting(conn, "curriculum_ver", "") == ver:
        return
    conn.execute("DELETE FROM tasks WHERE COALESCE(custom,0)=0")
    conn.execute("DELETE FROM units WHERE id NOT IN (SELECT DISTINCT unit_id FROM tasks)")
    conn.execute("DELETE FROM terms")
    for term in data.get("terms", []):
        conn.execute("INSERT INTO terms(id,label,grade,term,version) VALUES(?,?,?,?,?)",
                     (term["id"], term["label"], term["grade"], term["term"], term["version"]))
    for u in data["units"]:
        _upsert_unit(conn, u)
    for t in data["tasks"]:
        conn.execute(
            "INSERT INTO tasks(id,subject_id,unit_id,action,title,detail,sunshine,sort,custom) "
            "VALUES(?,?,?,?,?,?,?,?,0) "
            "ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id, unit_id=excluded.unit_id, "
            "action=excluded.action, title=excluded.title, detail=excluded.detail, "
            "sunshine=excluded.sunshine, sort=excluded.sort, custom=excluded.custom",
            (t["id"], t["subject"], t["unit_id"], t["action"], t["title"], t.get("detail", ""), t["sunshine"], t["sort"]))
    for d in data.get("daily_tasks", []):
        br = d.get("bonus_rule") or {}
        conn.execute(
            "INSERT INTO daily_tasks(id,subject_id,name,sunshine,frequency,bonus_type,bonus_per_metric,note) "
            "VALUES(?,?,?,?,?,?,?,?) "
            "ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id, name=excluded.name, "
            "sunshine=excluded.sunshine, frequency=excluded.frequency, bonus_type=excluded.bonus_type, "
            "bonus_per_metric=excluded.bonus_per_metric, note=excluded.note",
            (d["id"], d["subject"], d["name"], d["sunshine"], d["frequency"],
             br.get("type"), br.get("per_metric"), d.get("note", "")))
        conn.execute("DELETE FROM daily_metrics WHERE task_id=?", (d["id"],))
        for m in d.get("metrics", []):
            conn.execute(
                "INSERT INTO daily_metrics(task_id,id,label,unit,direction,note) "
                "VALUES(?,?,?,?,?,?) "
                "ON CONFLICT(task_id, id) DO UPDATE SET label=excluded.label, unit=excluded.unit, "
                "direction=excluded.direction, note=excluded.note",
                (d["id"], m["id"], m["label"], m["unit"], m["direction"], m.get("note")))
    set_setting(conn, "curriculum_ver", ver)


def migrate_task_ids(conn):
    """把旧（无学期前缀）单元任务/游标 id 归一为 g5s1-*，保证跨学期不撞旧完成记录（幂等）。
    daily_tasks 的 id（cn-read/cn-pen/cn-diary/ma-calc/en-phonics 等）不带学期前缀，必须排除，否则会被误加 g5s1- 前缀。"""
    for p in ("cn-", "ma-", "en-"):
        conn.execute(
            "UPDATE completions SET task_id='g5s1-'||task_id "
            "WHERE task_id LIKE ? AND task_id NOT LIKE ? "
            "AND task_id NOT IN (SELECT id FROM daily_tasks)", (p + "%", "g5s1-%"))
    conn.execute(
        "UPDATE settings SET value='g5s1-'||value WHERE key LIKE ? "
        "AND value != '' AND value NOT LIKE ?", ("cursor_%", "g5s1-%"))


def _has_column(conn, table, col):
    if conn.pg:
        return conn.execute(
            "SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name=? AND column_name=?",
            (table, col)).fetchone() is not None
    return any(r["name"] == col for r in conn.execute(f"PRAGMA table_info({table})").fetchall())


def _has_table(conn, name):
    if conn.pg:
        return conn.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=?",
            (name,)).fetchone() is not None
    return conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (name,)).fetchone() is not None


def _add_column(conn, table, spec):
    col = spec.split()[0]
    if not _has_column(conn, table, col):
        conn.execute(f"ALTER TABLE {table} ADD COLUMN {spec}")


def _migrate_001(conn):
    ts = now()
    conn.executescript("""
CREATE TABLE IF NOT EXISTS schema_migrations (id TEXT PRIMARY KEY, applied_at TEXT);
CREATE TABLE IF NOT EXISTS families (id TEXT PRIMARY KEY, name TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY, family_id TEXT, role TEXT NOT NULL,
  name TEXT, avatar TEXT DEFAULT '', pin_hash TEXT, term_id TEXT, created_at TEXT,
  parent_role TEXT DEFAULT 'member');
CREATE TABLE IF NOT EXISTS profiles (user_id TEXT PRIMARY KEY, family_id TEXT);
CREATE TABLE IF NOT EXISTS kid_settings (kid_id TEXT, key TEXT, value TEXT, PRIMARY KEY(kid_id, key));
""")
    conn.execute("INSERT INTO families(id,name,created_at) VALUES(?,?,?) ON CONFLICT DO NOTHING",
                 (DEFAULT_FAMILY, "默认家庭", ts))
    name = get_setting(conn, "kid_name", "乐乐") or "乐乐"
    term = get_setting(conn, "active_term", "g5s1") or "g5s1"
    conn.execute(
        "INSERT INTO users(id,family_id,role,name,avatar,pin_hash,term_id,created_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING",
        (DEFAULT_KID, DEFAULT_FAMILY, "kid", name, "", "", term, ts))
    conn.execute(
        "INSERT INTO users(id,family_id,role,name,avatar,pin_hash,term_id,created_at,parent_role) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING",
        (DEFAULT_PARENT, DEFAULT_FAMILY, "parent", "家长", "", "", None, ts, "owner"))
    conn.execute("INSERT INTO profiles(user_id,family_id) VALUES(?,?) ON CONFLICT DO NOTHING",
                 (DEFAULT_KID, DEFAULT_FAMILY))
    conn.execute("INSERT INTO profiles(user_id,family_id) VALUES(?,?) ON CONFLICT DO NOTHING",
                 (DEFAULT_PARENT, DEFAULT_FAMILY))


def _migrate_002(conn):
    for t in ("checkins", "completions", "ledger", "redemptions", "tests"):
        _add_column(conn, t, f"kid_id TEXT NOT NULL DEFAULT '{DEFAULT_KID}'")
        conn.execute(f"UPDATE {t} SET kid_id=? WHERE kid_id IS NULL OR kid_id=''", (DEFAULT_KID,))
    for t in ("rewards", "ranks"):
        _add_column(conn, t, f"family_id TEXT NOT NULL DEFAULT '{DEFAULT_FAMILY}'")
        conn.execute(f"UPDATE {t} SET family_id=? WHERE family_id IS NULL OR family_id=''", (DEFAULT_FAMILY,))
    _add_column(conn, "tasks", "family_id TEXT")
    _add_column(conn, "tasks", "kid_id TEXT")
    conn.execute("UPDATE tasks SET family_id=? WHERE COALESCE(custom,0)=1 AND family_id IS NULL",
                 (DEFAULT_FAMILY,))
    # P2 接线前：这里只 COPY，读写仍走 settings（无 RLS）。多娃前必改 get/set。
    for r in conn.execute(
            "SELECT key,value FROM settings WHERE key LIKE ? OR key LIKE ? OR key='box_opened'",
            ("cursor_%", "milestone_%")).fetchall():
        conn.execute(
            "INSERT INTO kid_settings(kid_id,key,value) VALUES(?,?,?) ON CONFLICT(kid_id, key) DO NOTHING",
            (DEFAULT_KID, r["key"], r["value"]))
    conn.commit()
    for idx in ("ux_cmp_unit", "ux_cmp_daily", "ux_chk_date"):
        conn.execute(f"DROP INDEX IF EXISTS {idx}")
    for ddl in (
        "CREATE UNIQUE INDEX IF NOT EXISTS ux_cmp_unit ON completions(kid_id, task_id) WHERE status='completed' AND kind='unit'",
        "CREATE UNIQUE INDEX IF NOT EXISTS ux_cmp_daily ON completions(kid_id, task_id, date) WHERE status='completed' AND kind='daily'",
        "CREATE UNIQUE INDEX IF NOT EXISTS ux_chk_date ON checkins(kid_id, date)",
    ):
        try:
            conn.execute(ddl)
        except Exception as e:
            print("[sunshine] index warn:", e)
            if conn.pg:
                conn._raw.rollback()


def _migrate_003(conn):
    if not conn.pg:
        return
    kid_tables = ("checkins", "completions", "ledger", "redemptions", "tests", "kid_settings")
    fam_tables = ("rewards", "ranks")
    for t in kid_tables:
        conn.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY")
        conn.execute(f"ALTER TABLE {t} FORCE ROW LEVEL SECURITY")
        conn.execute(f"DROP POLICY IF EXISTS iso ON {t}")
        conn.execute(
            f"CREATE POLICY iso ON {t} USING (kid_id = current_setting('app.kid_id', true)) "
            f"WITH CHECK (kid_id = current_setting('app.kid_id', true))")
    for t in fam_tables:
        conn.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY")
        conn.execute(f"ALTER TABLE {t} FORCE ROW LEVEL SECURITY")
        conn.execute(f"DROP POLICY IF EXISTS iso ON {t}")
        conn.execute(
            f"CREATE POLICY iso ON {t} USING (family_id = current_setting('app.family_id', true)) "
            f"WITH CHECK (family_id = current_setting('app.family_id', true))")
    conn.execute("ALTER TABLE tasks ENABLE ROW LEVEL SECURITY")
    conn.execute("ALTER TABLE tasks FORCE ROW LEVEL SECURITY")
    conn.execute("DROP POLICY IF EXISTS iso ON tasks")
    conn.execute(
        "CREATE POLICY iso ON tasks USING ("
        "COALESCE(custom,0)=0 OR (family_id = current_setting('app.family_id', true) "
        "AND (kid_id IS NULL OR kid_id = current_setting('app.kid_id', true)))) "
        "WITH CHECK ("
        "COALESCE(custom,0)=0 OR (family_id = current_setting('app.family_id', true) "
        "AND (kid_id IS NULL OR kid_id = current_setting('app.kid_id', true))))")
    # FORCE RLS 管不住 superuser。运行时必须 DATABASE_APP_URL 直接以 sunshine_app 登录。
    app_password = os.environ.get("DATABASE_APP_PASSWORD", "sunshine")
    if app_password == "sunshine":
        import sys
        print("⚠️  警告: DATABASE_APP_PASSWORD 未设置，使用默认密码 'sunshine'，生产环境必须设置强密码！", file=sys.stderr)
    conn.execute(f"""
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='sunshine_app') THEN
    CREATE ROLE sunshine_app LOGIN PASSWORD '{app_password}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
  END IF;
END $$;
""")
    conn.execute("GRANT CONNECT ON DATABASE sunshine TO sunshine_app")
    conn.execute("GRANT USAGE ON SCHEMA public TO sunshine_app")
    conn.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sunshine_app")
    conn.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sunshine_app")
    conn.execute("ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sunshine_app")
    conn.execute("ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO sunshine_app")


def _migrate_004(conn):
    _add_column(conn, "users", "account TEXT")
    conn.execute("UPDATE users SET account='parent' WHERE id=? AND (account IS NULL OR account='')",
                 (DEFAULT_PARENT,))
    conn.execute("UPDATE users SET account='lele' WHERE id=? AND (account IS NULL OR account='')",
                 (DEFAULT_KID,))
    conn.execute("CREATE UNIQUE INDEX IF NOT EXISTS ux_users_account ON users(account) WHERE account IS NOT NULL AND account != ''")
    conn.executescript("CREATE TABLE IF NOT EXISTS revoked (jti TEXT PRIMARY KEY, created_at TEXT);")
    pin = get_setting(conn, "admin_pin", "8888") or "8888"
    row = conn.execute("SELECT pin_hash FROM users WHERE id=?", (DEFAULT_PARENT,)).fetchone()
    if not (row and row["pin_hash"]):
        conn.execute("UPDATE users SET pin_hash=? WHERE id=?", (hash_pin(pin), DEFAULT_PARENT))
    kid = conn.execute("SELECT pin_hash FROM users WHERE id=?", (DEFAULT_KID,)).fetchone()
    if not (kid and kid["pin_hash"]):
        conn.execute("UPDATE users SET pin_hash=? WHERE id=?", (hash_pin(pin), DEFAULT_KID))  # P1 娃默认同 PIN，P2 再拆
    conn.execute("DELETE FROM settings WHERE key='admin_pin'")
    conn.execute("INSERT INTO settings(key,value) VALUES('force_pin_change','1') ON CONFLICT DO NOTHING")
    if conn.pg:
        conn.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sunshine_app")
        conn.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sunshine_app")


def _migrate_005(conn):
    _add_column(conn, "users", "force_pin_change TEXT DEFAULT '1'")
    # None=没键→仍强制；''=家长 P1 已改→不再强制。DEFAULT '1' 已写过，必须全表覆盖。
    raw = conn.execute("SELECT value FROM settings WHERE key='force_pin_change'").fetchone()
    flag = "1" if raw is None else (raw["value"] or "")
    conn.execute("UPDATE users SET force_pin_change=?", (flag,))
    conn.execute("DELETE FROM settings WHERE key='force_pin_change'")
    if conn.pg:
        conn.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sunshine_app")


def _migrate_006(conn):
    if not conn.pg:
        return
    conn.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY")
    conn.execute("ALTER TABLE users FORCE ROW LEVEL SECURITY")
    conn.execute("DROP POLICY IF EXISTS iso ON users")
    conn.execute(
        "CREATE POLICY iso ON users USING (family_id = current_setting('app.family_id', true)) "
        "WITH CHECK (family_id = current_setting('app.family_id', true))")


def _migrate_007(conn):
    conn.executescript("""
CREATE TABLE IF NOT EXISTS invites (
  code TEXT PRIMARY KEY, family_id TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'parent', created_at TEXT);
""")
    if conn.pg:
        conn.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sunshine_app")


def _migrate_008(conn):
    if not conn.pg:
        return
    conn.execute("ALTER TABLE invites ENABLE ROW LEVEL SECURITY")
    conn.execute("ALTER TABLE invites FORCE ROW LEVEL SECURITY")
    conn.execute("DROP POLICY IF EXISTS iso ON invites")
    conn.execute(
        "CREATE POLICY iso ON invites USING (family_id = current_setting('app.family_id', true)) "
        "WITH CHECK (family_id = current_setting('app.family_id', true))")


def _migrate_009(conn):
    _add_column(conn, "families", "invite_protect INTEGER DEFAULT 0")
    _add_column(conn, "invites", "max_uses INTEGER DEFAULT 0")
    _add_column(conn, "invites", "expires_at TEXT")
    _add_column(conn, "invites", "used_count INTEGER DEFAULT 0")


def _migrate_010(conn):
    _add_column(conn, "invites", "used_by TEXT")
    _add_column(conn, "invites", "used_at TEXT")


def _migrate_011(conn):
    _add_column(conn, "daily_tasks", "family_id TEXT")  # NULL=系统共享只读
    if not conn.pg:
        return
    conn.execute("ALTER TABLE daily_tasks ENABLE ROW LEVEL SECURITY")
    conn.execute("ALTER TABLE daily_tasks FORCE ROW LEVEL SECURITY")
    conn.execute("DROP POLICY IF EXISTS iso ON daily_tasks")
    conn.execute(
        "CREATE POLICY iso ON daily_tasks USING ("
        "family_id IS NULL OR family_id = current_setting('app.family_id', true)) "
        "WITH CHECK (family_id IS NULL OR family_id = current_setting('app.family_id', true))")
    conn.execute("ALTER TABLE profiles ENABLE ROW LEVEL SECURITY")
    conn.execute("ALTER TABLE profiles FORCE ROW LEVEL SECURITY")
    conn.execute("DROP POLICY IF EXISTS iso ON profiles")
    conn.execute(
        "CREATE POLICY iso ON profiles USING (family_id = current_setting('app.family_id', true)) "
        "WITH CHECK (family_id = current_setting('app.family_id', true))")


def _migrate_012(conn):
    if not conn.pg:
        return
    conn.execute("ALTER TABLE daily_metrics ENABLE ROW LEVEL SECURITY")
    conn.execute("ALTER TABLE daily_metrics FORCE ROW LEVEL SECURITY")
    conn.execute("DROP POLICY IF EXISTS iso ON daily_metrics")
    conn.execute(
        "CREATE POLICY iso ON daily_metrics USING (EXISTS ("
        "  SELECT 1 FROM daily_tasks dt WHERE dt.id = daily_metrics.task_id AND "
        "  (dt.family_id IS NULL OR dt.family_id = current_setting('app.family_id', true)))) "
        "WITH CHECK (EXISTS ("
        "  SELECT 1 FROM daily_tasks dt WHERE dt.id = daily_metrics.task_id AND "
        "  (dt.family_id IS NULL OR dt.family_id = current_setting('app.family_id', true))))")


def _migrate_013(conn):
    # 家长密码 ≥8 位上线：存量 parent 首登强制改密一次（密码存哈希，无法判断位数，统一强制）
    conn.execute("UPDATE users SET force_pin_change='1' WHERE role='parent'")
    conn.execute("UPDATE rewards SET need_approval=1 WHERE COALESCE(need_approval,0)=0")


def _migrate_014(conn):
    _add_column(conn, "families", "insight_rules TEXT DEFAULT ''")


def seed_fitness_standards(conn):
    path = BASE.parent / "data" / "fitness_standards.json"
    rows = json.loads(path.read_text(encoding="utf-8"))["rows"]
    for r in rows:
        conn.execute(
            "INSERT INTO fitness_standards(grade,gender,item,pass_value,good_value,excellent_value,unit,direction) "
            "VALUES(?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING",
            (r["grade"], r["gender"], r["item"], r["pass_value"], r.get("good_value"),
             r.get("excellent_value"), r["unit"], r.get("direction", "high")))


def _migrate_015(conn):
    _add_column(conn, "users", "gender TEXT")
    conn.execute("""
CREATE TABLE IF NOT EXISTS fitness_standards (
  grade INTEGER NOT NULL, gender TEXT NOT NULL, item TEXT NOT NULL,
  pass_value REAL, good_value REAL, excellent_value REAL,
  unit TEXT, direction TEXT DEFAULT 'high',
  PRIMARY KEY (grade, gender, item))
""")
    seed_fitness_standards(conn)


# 江苏南通现用版：语文部编 / 数学苏教 / 英语译林 / 科学苏教 / 道法部编
UNIT_EDITION = {
    "语文": "rjb-yuwen",
    "数学": "sjb-math",
    "英语": "yilin-eng",
    "科学": "sjb-sci",
    "道法": "rjb-daofa",
}


def unit_edition(subject, uid=""):
    if str(uid).startswith("custom"):
        return None
    return UNIT_EDITION.get(subject)


def _migrate_016(conn):
    _add_column(conn, "units", "version TEXT")
    for subj, ver in UNIT_EDITION.items():
        conn.execute(
            "UPDATE units SET version=? WHERE subject_id=? AND (version IS NULL OR version='')",
            (ver, subj))


def seed_knowledge_tags(conn):
    path = BASE.parent / "data" / "knowledge_tags.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    for t in data["tags"]:
        conn.execute(
            "INSERT INTO knowledge_tags(id,subject_id,kind,name) VALUES(?,?,?,?) "
            "ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id, kind=excluded.kind, name=excluded.name",
            (t["id"], t["subject_id"], t["kind"], t["name"]))
    conn.execute("DELETE FROM unit_tags")
    for u in data["unit_tags"]:
        auto = 1 if u.get("auto") else 0
        for tid in u.get("tag_ids") or []:
            conn.execute(
                "INSERT INTO unit_tags(unit_id,tag_id,auto) VALUES(?,?,?) ON CONFLICT DO NOTHING",
                (u["unit_id"], tid, auto))


def _migrate_018(conn):
    pk = ("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if conn.pg else "INTEGER PRIMARY KEY AUTOINCREMENT")
    conn.execute(f"""
CREATE TABLE IF NOT EXISTS weak_points (
  id {pk},
  kid_id TEXT NOT NULL, unit_id TEXT NOT NULL, tag_id TEXT NOT NULL,
  note TEXT DEFAULT '', status TEXT NOT NULL DEFAULT 'open',
  interval_idx INTEGER NOT NULL DEFAULT 0, review_due_at TEXT,
  created_at TEXT, updated_at TEXT)
""")
    conn.execute("CREATE INDEX IF NOT EXISTS ix_wp_kid ON weak_points(kid_id)")
    conn.execute("CREATE INDEX IF NOT EXISTS ix_wp_kid_unit ON weak_points(kid_id, unit_id)")
    if conn.pg:
        conn.execute("ALTER TABLE weak_points ENABLE ROW LEVEL SECURITY")
        conn.execute("ALTER TABLE weak_points FORCE ROW LEVEL SECURITY")
        conn.execute("DROP POLICY IF EXISTS iso ON weak_points")
        conn.execute(
            "CREATE POLICY iso ON weak_points USING (kid_id = current_setting('app.kid_id', true)) "
            "WITH CHECK (kid_id = current_setting('app.kid_id', true))")
        conn.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON weak_points TO sunshine_app")
        conn.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sunshine_app")


def _migrate_019(conn):
    # 五上语文考点精标（统编语文要素）：重跑 seed（tags upsert + 重建 unit_tags 映射）
    seed_knowledge_tags(conn)


def _migrate_020(conn):
    # 五上数英考点精标（苏教数学 + 译林英语）：重跑 seed
    seed_knowledge_tags(conn)


def _migrate_021(conn):
    # 五上语数英考点改为家长可判断的复习项目：重跑 seed，保留已有弱项记录。
    seed_knowledge_tags(conn)


def _migrate_022(conn):
    # 五上科学、道法按 2026 秋教材目录补齐人工考点映射。
    seed_knowledge_tags(conn)


def _migrate_023(conn):
    # 五上考点区去掉跨单元重复的基础练习，只保留单元特有难点。
    # weak_points 不动，避免删除家长已经记录的复习历史。
    seed_knowledge_tags(conn)


def _migrate_024(conn):
    # 旧版本取消只写冲正流水，历史完成记录仍为 completed，会挡住重新打卡。
    # 按对应冲正流水将这些记录标为 cancelled，保留完整审计链。
    conn.execute(
        "UPDATE completions SET status='cancelled' WHERE status='completed' AND EXISTS ("
        "SELECT 1 FROM ledger WHERE reason='cancel' AND ref_id='cmp-' || CAST(completions.id AS TEXT))"
    )


def _migrate_025(conn):
    """家长角色权限区分：owner(创建者) vs member(普通成员)"""
    _add_column(conn, "users", "parent_role TEXT DEFAULT 'member'")
    
    # 每个家庭的第一个家长（注册时间最早）设为创建者
    if is_postgres():
        conn.execute("""
            WITH first_parents AS (
                SELECT DISTINCT ON (family_id) id
                FROM users
                WHERE role='parent'
                ORDER BY family_id, created_at, id
            )
            UPDATE users
            SET parent_role = 'owner'
            WHERE id IN (SELECT id FROM first_parents)
        """)
    else:
        # SQLite: 使用 MIN(id) 作为代理（id 是自增的）
        conn.execute("""
            UPDATE users
            SET parent_role = 'owner'
            WHERE id IN (
                SELECT MIN(id)
                FROM users
                WHERE role='parent'
                GROUP BY family_id
            )
        """)



def _migrate_026(conn):
    _add_column(conn, "families", "penalty_enabled INTEGER DEFAULT 0")


def _migrate_031(conn):
    """一次性流水幂等：取消/开箱/扣分撤回/兑换/删测试/里程碑/单词奖励，并发连点只落一笔。"""
    reasons = (
        "'cancel','box','penalty_cancel','redeem','test_cancel',"
        "'milestone','word_daily','word_perfect'"
    )
    conn.execute(
        "DELETE FROM ledger WHERE id IN ("
        "SELECT l.id FROM ledger l "
        "JOIN ledger d ON d.kid_id=l.kid_id AND d.reason=l.reason "
        "AND IFNULL(d.ref_id,'')=IFNULL(l.ref_id,'') AND d.id<l.id "
        f"WHERE l.reason IN ({reasons}))"
    )
    conn.execute("DROP INDEX IF EXISTS ux_ledger_word_reward")
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS ux_ledger_once "
        f"ON ledger(kid_id, reason, ref_id) WHERE reason IN ({reasons})"
    )


def _migrate_034(conn):
    """阳光图鉴：kid_sprites + sprite_opens。033 已是银行利息。"""
    pk = ("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if conn.pg else "INTEGER PRIMARY KEY AUTOINCREMENT")
    conn.execute(f"""
CREATE TABLE IF NOT EXISTS kid_sprites (
  id {pk},
  kid_id TEXT NOT NULL,
  family_id TEXT NOT NULL,
  def_id TEXT NOT NULL,
  nickname TEXT NOT NULL DEFAULT '',
  flavor TEXT NOT NULL DEFAULT '',
  stars INTEGER NOT NULL DEFAULT 0,
  obtained_at TEXT NOT NULL,
  UNIQUE (kid_id, def_id)
)""")
    conn.execute("CREATE INDEX IF NOT EXISTS ix_kid_sprites_fam ON kid_sprites(family_id, kid_id)")
    conn.execute(f"""
CREATE TABLE IF NOT EXISTS sprite_opens (
  id {pk},
  kid_id TEXT NOT NULL,
  family_id TEXT NOT NULL,
  def_id TEXT NOT NULL,
  duplicate INTEGER NOT NULL DEFAULT 0,
  dust_gain INTEGER NOT NULL DEFAULT 0,
  source TEXT NOT NULL,
  ref_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE (kid_id, source, ref_id)
)""")
    if conn.pg:
        for t in ("kid_sprites", "sprite_opens"):
            conn.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY")
            conn.execute(f"ALTER TABLE {t} FORCE ROW LEVEL SECURITY")
            conn.execute(f"DROP POLICY IF EXISTS iso ON {t}")
            conn.execute(
                f"CREATE POLICY iso ON {t} USING (kid_id = current_setting('app.kid_id', true)) "
                f"WITH CHECK (kid_id = current_setting('app.kid_id', true))"
            )
            conn.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {t} TO sunshine_app")
        conn.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sunshine_app")


def _migrate_032(conn):
    """阳光银行：口袋/银行分账、一个目标、取出申请。旧流水均为口袋。"""
    _add_column(conn, "ledger", "account TEXT NOT NULL DEFAULT 'pocket'")
    conn.execute("UPDATE ledger SET account='pocket' WHERE account IS NULL OR account=''" )
    conn.execute("""
CREATE TABLE IF NOT EXISTS bank_goals (
  id TEXT PRIMARY KEY,
  kid_id TEXT NOT NULL,
  family_id TEXT NOT NULL,
  name TEXT NOT NULL,
  target INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  closed_at TEXT
)""")
    conn.execute("CREATE INDEX IF NOT EXISTS ix_bank_goals_kid ON bank_goals(kid_id, status)")
    conn.execute("""
CREATE TABLE IF NOT EXISTS bank_requests (
  id TEXT PRIMARY KEY,
  kid_id TEXT NOT NULL,
  family_id TEXT NOT NULL,
  kind TEXT NOT NULL,
  amount INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  note TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  handled_at TEXT
)""")
    conn.execute("CREATE INDEX IF NOT EXISTS ix_bank_requests_family ON bank_requests(family_id, status, created_at)")
    if conn.pg:
        for t in ("bank_goals", "bank_requests"):
            conn.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY")
            conn.execute(f"ALTER TABLE {t} FORCE ROW LEVEL SECURITY")
            conn.execute(f"DROP POLICY IF EXISTS iso ON {t}")
            conn.execute(f"CREATE POLICY iso ON {t} USING (kid_id = current_setting('app.kid_id', true)) WITH CHECK (kid_id = current_setting('app.kid_id', true))")
            conn.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {t} TO sunshine_app")


def _migrate_033(conn):
    """阳光银行利息：周期结算、起存点、家长可配置利率。"""
    # kid_settings 已有表，不需要新建，只是约定几个键：
    # bank_interest_enabled: "1"/"0"
    # bank_interest_cycle: "weekly"/"biweekly"/"monthly"
    # bank_interest_rate: "5.0" (百分比)
    # bank_interest_threshold: "20" (起存点)
    # bank_last_settle_date: "YYYY-MM-DD"
    pass


def _migrate_029(conn):
    """英语单词：系统/家庭词书、进度、session、attempts。先种子 Unit 1。"""
    pk = ("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if conn.pg else "INTEGER PRIMARY KEY AUTOINCREMENT")
    conn.execute("""
CREATE TABLE IF NOT EXISTS word_books (
  id TEXT PRIMARY KEY,
  family_id TEXT NOT NULL DEFAULT '',
  term_id TEXT NOT NULL DEFAULT '',
  unit_id TEXT,
  name TEXT NOT NULL,
  is_system INTEGER NOT NULL DEFAULT 0,
  enabled INTEGER NOT NULL DEFAULT 1,
  sort INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
)""")
    conn.execute("CREATE INDEX IF NOT EXISTS ix_word_books_family ON word_books(family_id, term_id, enabled, sort)")
    conn.execute(f"""
CREATE TABLE IF NOT EXISTS words (
  id {pk},
  book_id TEXT NOT NULL,
  word TEXT NOT NULL,
  word_norm TEXT NOT NULL,
  cn TEXT NOT NULL,
  ipa TEXT NOT NULL DEFAULT '',
  example_en TEXT NOT NULL DEFAULT '',
  example_cn TEXT NOT NULL DEFAULT '',
  accept_json TEXT NOT NULL DEFAULT '[]',
  sort INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(book_id, word_norm)
)""")
    conn.execute("CREATE INDEX IF NOT EXISTS ix_words_book_sort ON words(book_id, active, sort, id)")
    conn.execute("""
CREATE TABLE IF NOT EXISTS word_progress (
  kid_id TEXT NOT NULL,
  word_id INTEGER NOT NULL,
  interval_idx INTEGER NOT NULL DEFAULT 0,
  due_at TEXT,
  first_seen_at TEXT,
  last_seen_at TEXT,
  last_result TEXT NOT NULL DEFAULT '',
  streak_right INTEGER NOT NULL DEFAULT 0,
  correct_count INTEGER NOT NULL DEFAULT 0,
  wrong_count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (kid_id, word_id)
)""")
    conn.execute("CREATE INDEX IF NOT EXISTS ix_word_progress_due ON word_progress(kid_id, due_at, interval_idx)")
    conn.execute("""
CREATE TABLE IF NOT EXISTS word_sessions (
  id TEXT PRIMARY KEY,
  kid_id TEXT NOT NULL,
  family_id TEXT NOT NULL,
  study_date TEXT NOT NULL,
  book_ids_json TEXT NOT NULL,
  task_json TEXT NOT NULL,
  state TEXT NOT NULL DEFAULT 'active',
  started_at TEXT NOT NULL,
  completed_at TEXT,
  base_sunshine INTEGER NOT NULL DEFAULT 0,
  perfect_sunshine INTEGER NOT NULL DEFAULT 0,
  UNIQUE (kid_id, study_date)
)""")
    conn.execute("CREATE INDEX IF NOT EXISTS ix_word_sessions_kid_state ON word_sessions(kid_id, study_date, state)")
    conn.execute("CREATE INDEX IF NOT EXISTS ix_word_sessions_family_date ON word_sessions(family_id, study_date)")
    conn.execute(f"""
CREATE TABLE IF NOT EXISTS word_session_items (
  id {pk},
  session_id TEXT NOT NULL,
  kid_id TEXT NOT NULL,
  family_id TEXT NOT NULL,
  word_id INTEGER NOT NULL,
  source TEXT NOT NULL,
  item_order INTEGER NOT NULL,
  state TEXT NOT NULL DEFAULT 'study',
  first_result TEXT,
  retry_used INTEGER NOT NULL DEFAULT 0,
  answered_at TEXT,
  UNIQUE(session_id, word_id)
)""")
    conn.execute("CREATE INDEX IF NOT EXISTS ix_word_session_items_current ON word_session_items(session_id, state, item_order)")
    conn.execute(f"""
CREATE TABLE IF NOT EXISTS word_attempts (
  id {pk},
  session_id TEXT NOT NULL,
  kid_id TEXT NOT NULL,
  family_id TEXT NOT NULL,
  word_id INTEGER NOT NULL,
  phase TEXT NOT NULL,
  result TEXT NOT NULL,
  attempt_no INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE(session_id, word_id, phase, attempt_no)
)""")
    conn.execute("CREATE INDEX IF NOT EXISTS ix_word_attempts_session ON word_attempts(session_id, word_id)")
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS ux_ledger_word_reward "
        "ON ledger(kid_id, reason, ref_id) WHERE reason IN ('word_daily', 'word_perfect')"
    )
    if conn.pg:
        conn.execute("ALTER TABLE word_books ENABLE ROW LEVEL SECURITY")
        conn.execute("ALTER TABLE word_books FORCE ROW LEVEL SECURITY")
        conn.execute("DROP POLICY IF EXISTS iso ON word_books")
        conn.execute(
            "CREATE POLICY iso ON word_books USING ("
            "is_system=1 OR family_id = current_setting('app.family_id', true)) "
            "WITH CHECK (is_system=1 OR family_id = current_setting('app.family_id', true))"
        )
        for t in ("word_progress", "word_sessions", "word_session_items", "word_attempts"):
            conn.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY")
            conn.execute(f"ALTER TABLE {t} FORCE ROW LEVEL SECURITY")
            conn.execute(f"DROP POLICY IF EXISTS iso ON {t}")
            conn.execute(
                f"CREATE POLICY iso ON {t} USING (kid_id = current_setting('app.kid_id', true)) "
                f"WITH CHECK (kid_id = current_setting('app.kid_id', true))"
            )
        for t in ("word_books", "words", "word_progress", "word_sessions", "word_session_items", "word_attempts"):
            conn.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {t} TO sunshine_app")
        conn.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sunshine_app")
    import words as wordmod
    wordmod.seed_system_books(conn)


def _migrate_028(conn):
    """成就获得时刻：达标写一次，seen=0 表示还没看过新徽章动画。"""
    conn.execute("""
CREATE TABLE IF NOT EXISTS achievement_earned (
  kid_id TEXT NOT NULL,
  ach_id TEXT NOT NULL,
  family_id TEXT NOT NULL DEFAULT '',
  earned_at TEXT NOT NULL,
  seen INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (kid_id, ach_id)
)""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_ae_kid_seen ON achievement_earned(kid_id, seen)")
    if conn.pg:
        conn.execute("ALTER TABLE achievement_earned ENABLE ROW LEVEL SECURITY")
        conn.execute("ALTER TABLE achievement_earned FORCE ROW LEVEL SECURITY")
        conn.execute("DROP POLICY IF EXISTS iso ON achievement_earned")
        conn.execute(
            "CREATE POLICY iso ON achievement_earned USING (kid_id = current_setting('app.kid_id', true)) "
            "WITH CHECK (kid_id = current_setting('app.kid_id', true))")
        conn.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON achievement_earned TO sunshine_app")


def _migrate_027(conn):
    """家长一次性找回码哈希 + 登录/注册限流落库。"""
    _add_column(conn, "families", "recovery_hash TEXT")
    conn.execute("""
CREATE TABLE IF NOT EXISTS rate_limits (
  key TEXT NOT NULL,
  ts REAL NOT NULL
)""")
    conn.execute("CREATE INDEX IF NOT EXISTS ix_rate_limits_key_ts ON rate_limits(key, ts)")


def _migrate_017(conn):
    conn.execute("""
CREATE TABLE IF NOT EXISTS knowledge_tags (
  id TEXT PRIMARY KEY, subject_id TEXT, kind TEXT, name TEXT)
""")
    conn.execute("""
CREATE TABLE IF NOT EXISTS unit_tags (
  unit_id TEXT NOT NULL, tag_id TEXT NOT NULL, auto INTEGER DEFAULT 1,
  PRIMARY KEY (unit_id, tag_id))
""")
    seed_knowledge_tags(conn)


MIGRATIONS = (
    ("001_identity", _migrate_001),
    ("002_kid_id", _migrate_002),
    ("003_rls", _migrate_003),
    ("004_auth", _migrate_004),
    ("005_force_pin", _migrate_005),
    ("006_users_rls", _migrate_006),
    ("007_invites", _migrate_007),
    ("008_invites_rls", _migrate_008),
    ("009_invite_protect", _migrate_009),
    ("010_invite_usage", _migrate_010),
    ("011_daily_family", _migrate_011),
    ("012_daily_metrics_rls", _migrate_012),
    ("013_force_parent_pin", _migrate_013),
    ("014_insight_rules", _migrate_014),
    ("015_fitness", _migrate_015),
    ("016_unit_version", _migrate_016),
    ("017_knowledge_tags", _migrate_017),
    ("018_weak_points", _migrate_018),
    ("019_cn5_tags", _migrate_019),
    ("020_ma_en_tags", _migrate_020),
    ("021_g5s1_review_tags", _migrate_021),
    ("022_g5s1_kx_df_tags", _migrate_022),
    ("023_g5s1_unique_review_tags", _migrate_023),
    ("024_cancelled_recompletion", _migrate_024),
    ("025_parent_role", _migrate_025),
    ("026_penalty", _migrate_026),
    ("027_recovery_rate", _migrate_027),
    ("028_achievement_earned", _migrate_028),
    ("029_words", _migrate_029),
    ("031_ledger_once", _migrate_031),
    ("032_sunshine_bank", _migrate_032),
    ("033_bank_interest", _migrate_033),
    ("034_sprites", _migrate_034),
)


def apply_migrations(conn):
    conn.execute("CREATE TABLE IF NOT EXISTS schema_migrations (id TEXT PRIMARY KEY, applied_at TEXT)")
    conn.commit()
    for mid, fn in MIGRATIONS:
        if conn.execute("SELECT 1 FROM schema_migrations WHERE id=?", (mid,)).fetchone():
            continue
        if mid in ("003_rls", "006_users_rls", "008_invites_rls", "012_daily_metrics_rls") and not conn.pg:
            continue  # RLS 只在 PG 生效，SQLite 不记账
        fn(conn)
        conn.execute("INSERT INTO schema_migrations(id,applied_at) VALUES(?,?)", (mid, now()))
        conn.commit()


def fingerprints(conn):
    def n(q, params=()):
        return conn.execute(q, params).fetchone()[0]
    settings = {r["key"]: r["value"] for r in conn.execute("SELECT key,value FROM settings ORDER BY key")}
    return {
        "ledger_sum": n("SELECT COALESCE(SUM(delta),0) FROM ledger"),
        "earned_sum": n("SELECT COALESCE(SUM(delta),0) FROM ledger WHERE reason NOT IN ('redeem','bank_deposit','bank_withdraw')"),
        "ledger_n": n("SELECT COUNT(*) FROM ledger"),
        "completions": n("SELECT COUNT(*) FROM completions"),
        "checkins": n("SELECT COUNT(*) FROM checkins"),
        "redemptions": n("SELECT COUNT(*) FROM redemptions"),
        "tests": n("SELECT COUNT(*) FROM tests"),
        "daily_metrics": n("SELECT COUNT(*) FROM daily_metrics"),
        "settings": settings,
        "cursors": {k: v for k, v in settings.items() if k.startswith("cursor_")},
    }


def init_db():
    conn = connect(admin=True)
    conn.executescript(_schema())
    # SQLite 老库靠 ALTER 补列；PG 失败会整段事务作废，且建表已含这些列，跳过。
    if not conn.pg:
        for ddl in (
            "ALTER TABLE tasks ADD COLUMN custom INTEGER DEFAULT 0",
            "ALTER TABLE tasks ADD COLUMN detail TEXT DEFAULT ''",
            "ALTER TABLE completions ADD COLUMN kind TEXT NOT NULL DEFAULT 'unit'",
            "ALTER TABLE ranks ADD COLUMN icon TEXT DEFAULT ''",
            "ALTER TABLE tests ADD COLUMN unit_id TEXT",
            "ALTER TABLE daily_tasks ADD COLUMN note TEXT DEFAULT ''",
        ):
            try:
                conn.execute(ddl)
            except sqlite3.OperationalError:
                pass
    conn.commit()
    conn.execute("UPDATE completions SET kind='daily' WHERE task_id IN (SELECT id FROM daily_tasks)")
    apply_migrations(conn)
    # 系统考点映射来自 data/knowledge_tags.json；每次启动同步，避免旧库继续显示旧标签。
    # weak_points 从不在这里删除，家长已记录的复习历史会保留。
    seed_knowledge_tags(conn)
    import words as wordmod
    wordmod.seed_system_books(conn)
    migrate_task_ids(conn)
    if conn.execute("SELECT COUNT(*) FROM subjects").fetchone()[0] == 0:
        seed(conn)
    else:
        apply_curriculum(conn)
    for s in ALL_SUBJECTS:
        conn.execute("INSERT INTO subjects(id,name) VALUES(?,?) ON CONFLICT DO NOTHING", (s, s))
    conn.execute("INSERT INTO settings(key,value) VALUES('kid_name','乐乐') ON CONFLICT DO NOTHING")
    # 语文已学到《珍珠鸟》（g5s1-cn-1-5），推荐从这里往后，前面不加阳光
    conn.execute("INSERT INTO settings(key,value) VALUES('cursor_语文','g5s1-cn-1-5') ON CONFLICT DO NOTHING")
    conn.execute("INSERT INTO settings(key,value) VALUES('progress_lock','1') ON CONFLICT DO NOTHING")
    conn.execute("INSERT INTO settings(key,value) VALUES('active_term','g5s1') ON CONFLICT DO NOTHING")
    if get_setting(conn, "ranks_ver", "") != RANKS_VER:
        seed_ranks(conn)
    conn.commit()
    conn.close()


def get_setting(conn, key, default=None):
    r = conn.execute("SELECT value FROM settings WHERE key=?", (key,)).fetchone()
    return r["value"] if r else default


def set_setting(conn, key, value):
    conn.execute("INSERT INTO settings(key,value) VALUES(?,?) "
                 "ON CONFLICT(key) DO UPDATE SET value=excluded.value", (str(key), str(value)))


def get_kid_setting(conn, kid, key, default=None):
    r = conn.execute("SELECT value FROM kid_settings WHERE kid_id=? AND key=?", (kid, key)).fetchone()
    return r["value"] if r else default


def set_kid_setting(conn, kid, key, value):
    conn.execute(
        "INSERT INTO kid_settings(kid_id,key,value) VALUES(?,?,?) "
        "ON CONFLICT(kid_id, key) DO UPDATE SET value=excluded.value",
        (kid, key, str(value)))


def insert_ledger(conn, date, delta, reason, ref_id, note, kid_id, account="pocket"):
    """写入流水。一次性 reason 撞唯一索引时返回 None，不抛。"""
    return insert(
        conn,
        "INSERT INTO ledger(date,delta,reason,ref_id,note,created_at,kid_id,account) VALUES(?,?,?,?,?,?,?,?) "
        "ON CONFLICT DO NOTHING",
        (date, delta, reason, ref_id, note, now(), kid_id, account or "pocket"),
    )
